In [20]:
import numpy as np
a = [
        [8, 3, -3],
        [-2, -8, 5],
        [3, 5, 10]
]

diag = np.diag(np.abs(a))
print(diag)

[ 8  8 10]


In [21]:
np.sum(np.abs(a), axis = 1)

array([14, 15, 18])

In [22]:
offDiag = np.sum(np.abs(a), axis = 1) - diag
print(offDiag)

[6 7 8]


In [23]:
if np.all(diag > offDiag):
    print("Matrix is diagnolly dominant")
else:
    print("Not diagnolly dominant")
    

Matrix is diagnolly dominant


In [24]:
x1 = 0
x2 = 0
x3 = 0

epsilon = 0.001
converged = False

xOld = np.array([x1, x2, x3])

In [25]:
maxIteration = 50

In [26]:
print("Iteration reslults ")
print("k\tx1\tx2\tx3")

for k in range(1, maxIteration):
    x1 = (14 - 3*x2 + 3*x3)/8
    x2 = (5 + 2*x1 - 5*x3)/-8
    x3 = (-8 - 3*x1 - 5*x2)/10
    
    x = np.array([x1, x2, x3])
    print("%2d  %.4f  %.4f  %.4f" % (k, x1, x2, x3))
    
    dx = np.sqrt(np.dot(x-xOld, x-xOld))
    
    if dx < epsilon:
        converged = True
        print("Converged!")
        break
    
    x_old = x
    
if not converged:
    print("not converged increase the # of iterations")

Iteration reslults 
k	x1	x2	x3
 1  1.7500  -1.0625  -0.7937
 2  1.8508  -1.5838  -0.5633
 3  2.1327  -1.5103  -0.6847
 4  2.0596  -1.5678  -0.6340
 5  2.1002  -1.5463  -0.6569
 6  2.0835  -1.5565  -0.6468
 7  2.0911  -1.5520  -0.6513
 8  2.0878  -1.5540  -0.6493
 9  2.0893  -1.5531  -0.6502
10  2.0886  -1.5535  -0.6498
11  2.0889  -1.5534  -0.6500
12  2.0888  -1.5534  -0.6499
13  2.0888  -1.5534  -0.6499
14  2.0888  -1.5534  -0.6499
15  2.0888  -1.5534  -0.6499
16  2.0888  -1.5534  -0.6499
17  2.0888  -1.5534  -0.6499
18  2.0888  -1.5534  -0.6499
19  2.0888  -1.5534  -0.6499
20  2.0888  -1.5534  -0.6499
21  2.0888  -1.5534  -0.6499
22  2.0888  -1.5534  -0.6499
23  2.0888  -1.5534  -0.6499
24  2.0888  -1.5534  -0.6499
25  2.0888  -1.5534  -0.6499
26  2.0888  -1.5534  -0.6499
27  2.0888  -1.5534  -0.6499
28  2.0888  -1.5534  -0.6499
29  2.0888  -1.5534  -0.6499
30  2.0888  -1.5534  -0.6499
31  2.0888  -1.5534  -0.6499
32  2.0888  -1.5534  -0.6499
33  2.0888  -1.5534  -0.6499
34  2.0888  

In [28]:
8*x1 + 3*x2 -3*x3


14.000000000000002

In [29]:
-2*x1 -8*x2 +5*x3

5.0

In [30]:
3*x1 +5*x2 +10*x3

-7.999999999999999