In [3]:
import numpy as np
from numpy.linalg import inv

import scipy
from scipy.linalg import lu

In [4]:
#help(lu)


In [52]:
A = np.array([
            [1, 1, 1, 1],
            [2, 3, 1, 5],
            [-1, 1, -5, 3],
            [3, 1, 7, -2]
            ], dtype = float)

In [53]:
P, L, U = lu(A)

print("A:")
print(A)

print("P:")
print(P)

print("L:")
print(L)

print("U:")
print(U)


A:
[[ 1.  1.  1.  1.]
 [ 2.  3.  1.  5.]
 [-1.  1. -5.  3.]
 [ 3.  1.  7. -2.]]
P:
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
L:
[[ 1.          0.          0.          0.        ]
 [ 0.66666667  1.          0.          0.        ]
 [-0.33333333  0.57142857  1.          0.        ]
 [ 0.33333333  0.28571429  0.5         1.        ]]
U:
[[ 3.          1.          7.         -2.        ]
 [ 0.          2.33333333 -3.66666667  6.33333333]
 [ 0.          0.         -0.57142857 -1.28571429]
 [ 0.          0.          0.          0.5       ]]


In [54]:
L = P.dot(L)

In [55]:
L.dot(U)

array([[ 1.,  1.,  1.,  1.],
       [ 2.,  3.,  1.,  5.],
       [-1.,  1., -5.,  3.],
       [ 3.,  1.,  7., -2.]])

In [56]:
A

array([[ 1.,  1.,  1.,  1.],
       [ 2.,  3.,  1.,  5.],
       [-1.,  1., -5.,  3.],
       [ 3.,  1.,  7., -2.]])

In [57]:
L.dot(U) == A

array([[ True, False, False, False],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [58]:
np.allclose(L.dot(U), A)

True

In [59]:
y = np.array([10, 31, -2, 18])
y

array([10, 31, -2, 18])

Lm = y

let's move L to the other side of the question.

L-1 Lm = L-1y

and cancel out...

m = L-1y

In [60]:
m = inv(L).dot(y)
m

array([18.        , 19.        , -6.85714286,  2.        ])

In [61]:
x = inv(U).dot(m)
x

array([1., 2., 3., 4.])

In [62]:
yp = A.dot(x)
print(yp)

[10. 31. -2. 18.]


In [63]:
np.allclose(y, yp)

True