In [1]:
import numpy as np

In [2]:
np.random.seed(1337)

In [34]:
x = np.array([[1,3,4]])
x

array([[1, 3, 4]])

In [35]:
x.shape


(1, 3)

In [37]:
y = np.array([[1,4,5],[7,2,4]])

In [38]:
y.shape

(2, 3)

In [39]:
z = np.array([[[[3,5,6]]]])
z.shape

(1, 1, 1, 3)

In [12]:
z = np.arange(1,2000,1)
z[:20]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
z.shape

(1999,)

In [47]:
np.arange(0.5, 3, 0.5)

array([0.5, 1. , 1.5, 2. , 2.5])

In [44]:
np.arange(0.5, 10, 1).shape

(10,)

In [53]:
x = np.arange(0, 6, 1).reshape(6,1)
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [17]:
np.linspace(2, 2.1, 10)

array([2.        , 2.01111111, 2.02222222, 2.03333333, 2.04444444,
       2.05555556, 2.06666667, 2.07777778, 2.08888889, 2.1       ])

In [18]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [58]:
b = np.zeros((2, 2))
b


array([[0., 0.],
       [0., 0.]])

In [59]:
b[0 , 0] = 2
b[0 , 1] = 4
b[1 , 0] = 3
b[1 , 1] = 8
b

array([[2., 4.],
       [3., 8.]])

In [60]:
b.sum()

17.0

In [61]:
b.sum(axis=0)

array([ 5., 12.])

In [25]:
b.sum(axis=1)

array([ 6., 11.])

In [26]:
b = np.array([[1, 2], [3, 4]])
d = np.array([[1, 3], [1, 3]])

In [27]:
print(b)
print(d)

[[1 2]
 [3 4]]
[[1 3]
 [1 3]]


In [28]:
a = np.array([[2, 5, 7], [2, 4, 5]])
a

array([[2, 5, 7],
       [2, 4, 5]])

In [29]:
print(a)

[[2 5 7]
 [2 4 5]]


In [30]:
a.sum()

25

In [31]:
a.sum(axis = 0)

array([ 4,  9, 12])

In [32]:
a.sum(axis = 1)

array([14, 11])

In [45]:
b = np.array([1,2,3,4,5,6,7,8])
d = np.array([[1, 3], [1, 3]])

In [46]:
print(b)
print(d)

[1 2 3 4 5 6 7 8]
[[1 3]
 [1 3]]


In [47]:
b + d

ValueError: operands could not be broadcast together with shapes (8,) (2,2) 

In [36]:
b * d

array([[ 1,  6],
       [ 3, 12]])

In [48]:
b.dot(d)

ValueError: shapes (8,) and (2,2) not aligned: 8 (dim 0) != 2 (dim 0)

In [49]:
b.T


array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
b.shape


(8,)

In [50]:
b.T.shape


(8,)

In [53]:
print(np.sqrt(4))

x = [1, 4, 5, 16]
np.sqrt(x)

2.0


array([1.        , 2.        , 2.23606798, 4.        ])

In [54]:
x = np.array([12, 45, 56, 78])
y = np.array([23, 4, 6, 67])

In [55]:
x > 3


array([ True,  True,  True,  True])

In [56]:
x > 40

array([False,  True,  True,  True])

In [57]:
x > y


array([False,  True,  True,  True])